# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ProjectTest',
                'doc_host': 'https://lalithapavani-b.github.io',
                'git_url': 'https://github.com/lalithapavani-b/ProjectTest',
                'lib_path': 'ProjectTest'},
  'syms': {'ProjectTest.core': {'ProjectTest.core.foo': ('core.html#foo', 'ProjectTest/core.py')}}}
